### ISSUE TITLE
[Feature request] New release

### ISSUE THREAD

**Issue by rieje** [Hummer12007/brightnessctl#113] opened 2024-10-20 21:26 UTC
EDIT: As stated below it's been implemented, so a new release would be welcomed.

-------

Feature request: Get brightness value as a percentage. Working with percentage is more intuitive but also it's not clear if all displays have a max brightness of 7500 that my system reports. 

I want to manually handle saving and restoring brightness level depending on conditions--I set as using a percentage value but since the value reported by brightnessctl is e.g. 750, I need to manually determine this myself and in a way that might be system-dependent (if I'm on systems whose display has a max brightness different than 7500, then that would need to be handled as well.

**Comment by JohnMertz** [comment] 2024-10-25 23:35
If the maintainer is not creating new releases, you may need to contact your distribution maintainer to ask them to build from the latest commits. Otherwise you may need to build from source.

Note that my version from Fedora 40 does have this feature (hurray!), but I see that the Debian source package has not been updated since the latest GitHub release, and the Arch package is also directly built from the tar.gz from the GitHub releases, so it doesn't have it either.

**Comment by JohnMertz** [comment] 2024-10-26 16:59
With the new topic, this is a duplicate of at least #112 and #90. I think you can probably re-close this and comment on one of those issues if you have anything to add.

**Comment by PowerMan2206** [comment] 2024-10-27 14:14
I think we're gonna be waiting a while for a new release. Hummer's profile says he's from Kyiv, I don't think "releasing an update to a program so that people can see their screen brightness better" is in his priority list right about now.

**Comment by Hummer12007** [comment] 2024-12-12 15:16
Closed in favor of #90

**Closed by Hummer12007** 2024-12-12 15:16 UTC
