### ISSUE TITLE
No effect on brightness with Ubuntu 17.10 (wayland)

### ISSUE THREAD

**Issue by jorvis** [Hummer12007/brightnessctl#18] opened 2018-02-24 22:45 UTC
```
$ brightnessctl -l | head -n 5
Available devices:
Device 'intel_backlight' of class 'backlight':
	Current brightness: 1049 (98%)
	Max brightness: 1060
```

When I try to change it, nothing at all happens to the display brightness on the laptop (Yoga X1 v2)

```
$ brightnessctl -d intel_backlight s 50%
Updated device 'intel_backlight':
Device 'intel_backlight' of class 'backlight':
	Current brightness: 530 (50%)
	Max brightness: 1060
```

**Comment by Hummer12007** [comment] 2018-02-24 23:05
What are your other devices?

**Comment by jorvis** [comment] 2018-02-25 18:10
Here's the entire output

```
Available devices:
Device 'intel_backlight' of class 'backlight':
	Current brightness: 1049 (98%)
	Max brightness: 1060

Device 'tpacpi::thinkvantage' of class 'leds':
	Current brightness: 0 (0%)
	Max brightness: 255

Device 'tpacpi::standby' of class 'leds':
	Current brightness: 0 (0%)
	Max brightness: 255

Device 'tpacpi::kbd_backlight' of class 'leds':
	Current brightness: 0 (0%)
	Max brightness: 2

Device 'input3::scrolllock' of class 'leds':
	Current brightness: 0 (0%)
	Max brightness: 1

Device 'input3::capslock' of class 'leds':
	Current brightness: 0 (0%)
	Max brightness: 1

Device 'tpacpi::thinklight' of class 'leds':
	Current brightness: 0 (0%)
	Max brightness: 255

Device 'input3::numlock' of class 'leds':
	Current brightness: 0 (0%)
	Max brightness: 1

Device 'phy0-led' of class 'leds':
	Current brightness: 1 (100%)
	Max brightness: 1

Device 'tpacpi::power' of class 'leds':
	Current brightness: 0 (0%)
	Max brightness: 255
```

**Comment by Hummer12007** [comment] 2018-02-25 19:00
Have you tried these workarounds? https://wiki.ubuntu.com/Kernel/Debugging/Backlight#Diagnostic_Techniques

**Comment by Hummer12007** [comment] 2021-09-06 07:38
Probable duplicate of #63

**Closed by Hummer12007** 2021-09-06 07:38 UTC
